Homework
pavlosloboda/pharmagator pull request #1
Opened 2021-10-11 10:11 UTC by VolodymyrHoliev

2021-10-11 13:36 UTC, pavlosloboda requested changes

2021-10-11 13:36 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/MedicineController.java
> +    @GetMapping("/getById")
Please, read [this article](https://restfulapi.net/resource-naming/) and update paths.

E.g.:
getAll -> /medicines GET
getById -> /medicines/{medicineId} GET
create -> /medicines POST
deleteById -> /medicines/{medicineId} DELETE
update -> /medicines/{medicineId} PUT

2021-10-11 13:36 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/MedicineController.java
> +    public ResponseEntity<Medicine> getById(@RequestParam Long id) {
Resource id should be passed as PathVariable instead of RequestParam.

2021-10-11 13:36 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/MedicineController.java
> +            return ResponseEntity.ok().build();
Use NO_CONTENT (204) status code if you return nothing.

2021-10-11 13:36 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/MedicineController.java
> +    public ResponseEntity<?> create(@RequestBody Medicine medicine) {
Do not use wildcard in response. `ResponseEntity<Medicine>`

2021-10-11 13:36 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/MedicineController.java
> +    public ResponseEntity<?> deleteById(@RequestParam Long id) {
`ResponseEntity<Void>` if you return nothing

2021-10-11 13:36 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/MedicineController.java
> +    public ResponseEntity<?> update(@RequestBody Medicine medicine) {
`ResponseEntity<Medicine>`

2021-10-11 13:36 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PharmacyController.java
> +            pharmacyRepository.save(pharmacyById);
Actually, you can save received object without remapping to one from database

2021-10-11 13:36 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/repositories/PriceRepository.java
> +public interface PriceRepository extends JpaRepository<Price, Long> {
JpaRepository<Price, PriceId> should be here

2021-10-11 13:36 UTC, pavlosloboda commented on api/src/main/resources/db/migration/V1_0_1__add_relationships.sql
> +ALTER TABLE prices ADD CONSTRAINT  fk_pharmacy FOREIGN KEY(pharmacy_id) REFERENCES pharmacies(id);
Actually, you need only two last lines here

2021-10-13 07:06 UTC, pavlosloboda requested changes

2021-10-13 07:06 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PharmacyController.java
> +    @GetMapping("/getById")
Please, fix path

2021-10-13 07:06 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PharmacyController.java
> +    public ResponseEntity<?> deleteById(@PathVariable Long pharmacyId) {
Void

2021-10-13 07:06 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PriceController.java
> +    @GetMapping("/{priceId}")
This will not work. Need something like @GetMapping("/pharmacies/{pharmacyId}/medicines/{medicineId}")

2021-10-13 07:06 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PriceController.java
> +    public ResponseEntity<?> deleteById(@PathVariable PriceId priceId) {
Void

2021-10-13 07:06 UTC, pavlosloboda commented on api/src/test/resources/application-test.yaml
> +      ddl-auto: create-drop
It should be validate

2021-10-13 07:39 UTC, VolodymyrHoliev commented on api/src/test/java/com/eleks/academy/pharmagator/PharmagatorApplicationTests.java
> -	@Test
Basically,that test does nothing.I removed the test due to Travis CI build failure.I don`t know why,but it looks like Travis uses Postgre even for tests.While my test is doing nothing, I thought I could delete it and figure out what is wrong later.

PharmagatorApplicationTests > contextLoads() FAILED
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132
        Caused by: org.springframework.beans.factory.BeanCreationException at AbstractAutowireCapableBeanFactory.java:1804
            Caused by: org.flywaydb.core.internal.exception.FlywaySqlException at JdbcUtils.java:67
                Caused by: org.postgresql.util.PSQLException at QueryExecutorImpl.java:2565

2021-10-18 12:16 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PharmacyController.java
> +    public @ResponseBody ResponseEntity<List<Pharmacy>> getAll() {
You do not need @ResponseBody here

2021-10-18 12:16 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PharmacyController.java
> +    @GetMapping("/pharmacyId")
/pharmacyId -> /{pharmacyId}

2021-10-18 12:18 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PharmacyController.java
> +    public ResponseEntity<Pharmacy> update(@PathVariable Long pharmacyId,@RequestBody Pharmacy pharmacy) {
Use `Ctrl + Alt + L` to autoformat code

2021-10-18 12:19 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PriceController.java
> +    @GetMapping("/{priceId}")
Please, check the comment above

2021-10-18 12:20 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PriceController.java
> +    @PostMapping("/create")
@PostMapping("/create") -> @PostMapping

2021-10-18 12:21 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/PriceController.java
> +    @PutMapping("/{priceId}")
Please, fix path

2021-11-02 09:28 UTC, closed without merging